const heroes = ["Iron Man",
                "Thor",
                "Hulk",
                "Captain America",
                "Black Widow",
                "Dr. Strange",
                "War Machine",
                "Black Panther",
                "Vision",
                "Scarlet Witch",
                "Falcon",
                "White Wolf",
                "Heimdall",
                "Loki",
                "Eitri the Dwarf King",
                "Star-Lord",
                "Mantis",
                "Nebula",
                "Drax the Destroyer",
                "Gamora",
                "Groot",
                "Rocket",
                "Taneleer Tivan",
                "Thanos"];

export default heroes;
